//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.27 at 10:34:43 AM EST 
//


package gov.nih.ncgc.bard.capextract.jaxb;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="assayTitle">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="250"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="assayName">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="designedBy" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="assayContexts" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="assayContext" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="contextName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element ref="{}assayContextItems"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="measures" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="measure" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="resultTypeRef">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element ref="{}link" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="label" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="entryUnit" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element ref="{}link" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="unit" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="assayContextRef" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="parentMeasure" type="{}bardID" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{}assayContextItems" minOccurs="0"/>
 *         &lt;element name="assayDocuments" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}assayDocument" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{}link" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="assayId" type="{}bardID" />
 *       &lt;attribute name="assayVersion" default="1 ">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;maxLength value="10"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="status">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="Pending"/>
 *             &lt;enumeration value="Active"/>
 *             &lt;enumeration value="Superceded"/>
 *             &lt;enumeration value="Retired"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute ref="{}readyForExtraction"/>
 *       &lt;attribute name="assayType">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="Regular"/>
 *             &lt;enumeration value="Panel - Array"/>
 *             &lt;enumeration value="Panel - Group"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "assayTitle",
    "assayName",
    "designedBy",
    "assayContexts",
    "measures",
    "assayContextItems",
    "assayDocuments",
    "link"
})
@XmlRootElement(name = "assay")
public class Assay {

    @XmlElement(required = true, defaultValue = "")
    protected String assayTitle;
    @XmlElement(required = true)
    protected String assayName;
    protected String designedBy;
    protected Assay.AssayContexts assayContexts;
    protected Assay.Measures measures;
    protected AssayContextItems assayContextItems;
    protected Assay.AssayDocuments assayDocuments;
    @XmlElement(required = true)
    protected List<Link> link;
    @XmlAttribute(name = "assayId")
    protected BigInteger assayId;
    @XmlAttribute(name = "assayVersion")
    protected String assayVersion;
    @XmlAttribute(name = "status")
    protected String status;
    @XmlAttribute(name = "readyForExtraction")
    protected String readyForExtraction;
    @XmlAttribute(name = "assayType")
    protected String assayType;

    /**
     * Gets the value of the assayTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssayTitle() {
        return assayTitle;
    }

    /**
     * Sets the value of the assayTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssayTitle(String value) {
        this.assayTitle = value;
    }

    /**
     * Gets the value of the assayName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssayName() {
        return assayName;
    }

    /**
     * Sets the value of the assayName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssayName(String value) {
        this.assayName = value;
    }

    /**
     * Gets the value of the designedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDesignedBy() {
        return designedBy;
    }

    /**
     * Sets the value of the designedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDesignedBy(String value) {
        this.designedBy = value;
    }

    /**
     * Gets the value of the assayContexts property.
     * 
     * @return
     *     possible object is
     *     {@link Assay.AssayContexts }
     *     
     */
    public Assay.AssayContexts getAssayContexts() {
        return assayContexts;
    }

    /**
     * Sets the value of the assayContexts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Assay.AssayContexts }
     *     
     */
    public void setAssayContexts(Assay.AssayContexts value) {
        this.assayContexts = value;
    }

    /**
     * Gets the value of the measures property.
     * 
     * @return
     *     possible object is
     *     {@link Assay.Measures }
     *     
     */
    public Assay.Measures getMeasures() {
        return measures;
    }

    /**
     * Sets the value of the measures property.
     * 
     * @param value
     *     allowed object is
     *     {@link Assay.Measures }
     *     
     */
    public void setMeasures(Assay.Measures value) {
        this.measures = value;
    }

    /**
     * Gets the value of the assayContextItems property.
     * 
     * @return
     *     possible object is
     *     {@link AssayContextItems }
     *     
     */
    public AssayContextItems getAssayContextItems() {
        return assayContextItems;
    }

    /**
     * Sets the value of the assayContextItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssayContextItems }
     *     
     */
    public void setAssayContextItems(AssayContextItems value) {
        this.assayContextItems = value;
    }

    /**
     * Gets the value of the assayDocuments property.
     * 
     * @return
     *     possible object is
     *     {@link Assay.AssayDocuments }
     *     
     */
    public Assay.AssayDocuments getAssayDocuments() {
        return assayDocuments;
    }

    /**
     * Sets the value of the assayDocuments property.
     * 
     * @param value
     *     allowed object is
     *     {@link Assay.AssayDocuments }
     *     
     */
    public void setAssayDocuments(Assay.AssayDocuments value) {
        this.assayDocuments = value;
    }

    /**
     * Gets the value of the link property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the link property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLink().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Link }
     * 
     * 
     */
    public List<Link> getLink() {
        if (link == null) {
            link = new ArrayList<Link>();
        }
        return this.link;
    }

    /**
     * Gets the value of the assayId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAssayId() {
        return assayId;
    }

    /**
     * Sets the value of the assayId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAssayId(BigInteger value) {
        this.assayId = value;
    }

    /**
     * Gets the value of the assayVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssayVersion() {
        if (assayVersion == null) {
            return "1 ";
        } else {
            return assayVersion;
        }
    }

    /**
     * Sets the value of the assayVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssayVersion(String value) {
        this.assayVersion = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the readyForExtraction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReadyForExtraction() {
        return readyForExtraction;
    }

    /**
     * Sets the value of the readyForExtraction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReadyForExtraction(String value) {
        this.readyForExtraction = value;
    }

    /**
     * Gets the value of the assayType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssayType() {
        return assayType;
    }

    /**
     * Sets the value of the assayType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssayType(String value) {
        this.assayType = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="assayContext" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="contextName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element ref="{}assayContextItems"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "assayContext"
    })
    public static class AssayContexts {

        @XmlElement(required = true)
        protected List<Assay.AssayContexts.AssayContext> assayContext;

        /**
         * Gets the value of the assayContext property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the assayContext property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAssayContext().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Assay.AssayContexts.AssayContext }
         * 
         * 
         */
        public List<Assay.AssayContexts.AssayContext> getAssayContext() {
            if (assayContext == null) {
                assayContext = new ArrayList<Assay.AssayContexts.AssayContext>();
            }
            return this.assayContext;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="contextName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element ref="{}assayContextItems"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "contextName",
            "assayContextItems"
        })
        public static class AssayContext {

            @XmlElement(required = true)
            protected String contextName;
            @XmlElement(required = true)
            protected AssayContextItems assayContextItems;

            /**
             * Gets the value of the contextName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getContextName() {
                return contextName;
            }

            /**
             * Sets the value of the contextName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setContextName(String value) {
                this.contextName = value;
            }

            /**
             * Gets the value of the assayContextItems property.
             * 
             * @return
             *     possible object is
             *     {@link AssayContextItems }
             *     
             */
            public AssayContextItems getAssayContextItems() {
                return assayContextItems;
            }

            /**
             * Sets the value of the assayContextItems property.
             * 
             * @param value
             *     allowed object is
             *     {@link AssayContextItems }
             *     
             */
            public void setAssayContextItems(AssayContextItems value) {
                this.assayContextItems = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}assayDocument" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "assayDocument"
    })
    public static class AssayDocuments {

        @XmlElement(required = true)
        protected List<AssayDocument> assayDocument;

        /**
         * Gets the value of the assayDocument property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the assayDocument property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAssayDocument().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AssayDocument }
         * 
         * 
         */
        public List<AssayDocument> getAssayDocument() {
            if (assayDocument == null) {
                assayDocument = new ArrayList<AssayDocument>();
            }
            return this.assayDocument;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="measure" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="resultTypeRef">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element ref="{}link" minOccurs="0"/>
     *                           &lt;/sequence>
     *                           &lt;attribute name="label" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="entryUnit" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element ref="{}link" minOccurs="0"/>
     *                           &lt;/sequence>
     *                           &lt;attribute name="unit" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="assayContextRef" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="parentMeasure" type="{}bardID" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "measure"
    })
    public static class Measures {

        @XmlElement(required = true)
        protected List<Assay.Measures.Measure> measure;

        /**
         * Gets the value of the measure property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the measure property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMeasure().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Assay.Measures.Measure }
         * 
         * 
         */
        public List<Assay.Measures.Measure> getMeasure() {
            if (measure == null) {
                measure = new ArrayList<Assay.Measures.Measure>();
            }
            return this.measure;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="resultTypeRef">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element ref="{}link" minOccurs="0"/>
         *                 &lt;/sequence>
         *                 &lt;attribute name="label" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="entryUnit" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element ref="{}link" minOccurs="0"/>
         *                 &lt;/sequence>
         *                 &lt;attribute name="unit" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="assayContextRef" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="parentMeasure" type="{}bardID" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "resultTypeRef",
            "entryUnit"
        })
        public static class Measure {

            @XmlElement(required = true)
            protected Assay.Measures.Measure.ResultTypeRef resultTypeRef;
            protected Assay.Measures.Measure.EntryUnit entryUnit;
            @XmlAttribute(name = "assayContextRef")
            protected String assayContextRef;
            @XmlAttribute(name = "parentMeasure")
            protected BigInteger parentMeasure;

            /**
             * Gets the value of the resultTypeRef property.
             * 
             * @return
             *     possible object is
             *     {@link Assay.Measures.Measure.ResultTypeRef }
             *     
             */
            public Assay.Measures.Measure.ResultTypeRef getResultTypeRef() {
                return resultTypeRef;
            }

            /**
             * Sets the value of the resultTypeRef property.
             * 
             * @param value
             *     allowed object is
             *     {@link Assay.Measures.Measure.ResultTypeRef }
             *     
             */
            public void setResultTypeRef(Assay.Measures.Measure.ResultTypeRef value) {
                this.resultTypeRef = value;
            }

            /**
             * Gets the value of the entryUnit property.
             * 
             * @return
             *     possible object is
             *     {@link Assay.Measures.Measure.EntryUnit }
             *     
             */
            public Assay.Measures.Measure.EntryUnit getEntryUnit() {
                return entryUnit;
            }

            /**
             * Sets the value of the entryUnit property.
             * 
             * @param value
             *     allowed object is
             *     {@link Assay.Measures.Measure.EntryUnit }
             *     
             */
            public void setEntryUnit(Assay.Measures.Measure.EntryUnit value) {
                this.entryUnit = value;
            }

            /**
             * Gets the value of the assayContextRef property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAssayContextRef() {
                return assayContextRef;
            }

            /**
             * Sets the value of the assayContextRef property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAssayContextRef(String value) {
                this.assayContextRef = value;
            }

            /**
             * Gets the value of the parentMeasure property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getParentMeasure() {
                return parentMeasure;
            }

            /**
             * Sets the value of the parentMeasure property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setParentMeasure(BigInteger value) {
                this.parentMeasure = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element ref="{}link" minOccurs="0"/>
             *       &lt;/sequence>
             *       &lt;attribute name="unit" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "link"
            })
            public static class EntryUnit {

                protected Link link;
                @XmlAttribute(name = "unit", required = true)
                protected String unit;

                /**
                 * Gets the value of the link property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Link }
                 *     
                 */
                public Link getLink() {
                    return link;
                }

                /**
                 * Sets the value of the link property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Link }
                 *     
                 */
                public void setLink(Link value) {
                    this.link = value;
                }

                /**
                 * Gets the value of the unit property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getUnit() {
                    return unit;
                }

                /**
                 * Sets the value of the unit property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setUnit(String value) {
                    this.unit = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element ref="{}link" minOccurs="0"/>
             *       &lt;/sequence>
             *       &lt;attribute name="label" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "link"
            })
            public static class ResultTypeRef {

                protected Link link;
                @XmlAttribute(name = "label", required = true)
                protected String label;

                /**
                 * Gets the value of the link property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Link }
                 *     
                 */
                public Link getLink() {
                    return link;
                }

                /**
                 * Sets the value of the link property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Link }
                 *     
                 */
                public void setLink(Link value) {
                    this.link = value;
                }

                /**
                 * Gets the value of the label property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getLabel() {
                    return label;
                }

                /**
                 * Sets the value of the label property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setLabel(String value) {
                    this.label = value;
                }

            }

        }

    }

}
