//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.06.07 at 08:41:41 AM EDT 
//


package gov.nih.ncgc.bard.capextract.jaxb;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="elements">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}element" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="elementHierarchies">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="elementHierarchy" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="relationshipType">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;enumeration value="supported by"/>
 *                                   &lt;enumeration value="child of"/>
 *                                   &lt;enumeration value="has_a"/>
 *                                   &lt;enumeration value="derives from"/>
 *                                   &lt;enumeration value="is_a"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="parentElementId" type="{}bardID" />
 *                           &lt;attribute name="childElementId" use="required" type="{}bardID" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="resultTypes">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}resultType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="stages" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}stage" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="biologyDescriptors" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="biologyDescriptor" type="{}descriptorType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="assayDescriptors" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="assayDescriptor" type="{}descriptorType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="instanceDescriptors" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="instanceDescriptor" type="{}descriptorType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="laboratories" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="laboratory" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="laboratoryName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element ref="{}description" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="laboratoryId" use="required" type="{}bardID" />
 *                           &lt;attribute name="parentLaboratoryId" type="{}bardID" />
 *                           &lt;attribute name="laboratoryStatus" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="units" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="unit" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{}description" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="unitId" use="required" type="{}bardID" />
 *                           &lt;attribute name="parentUnitId" type="{}bardID" />
 *                           &lt;attribute name="unit" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="unitConversions" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="unitConversion" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="formula" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="fromUnit" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="toUnit" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="multiplier" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                           &lt;attribute name="offset" type="{http://www.w3.org/2001/XMLSchema}double" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "elements",
    "elementHierarchies",
    "resultTypes",
    "stages",
    "biologyDescriptors",
    "assayDescriptors",
    "instanceDescriptors",
    "laboratories",
    "units",
    "unitConversions"
})
@XmlRootElement(name = "dictionary")
public class Dictionary {

    @XmlElement(required = true)
    protected Dictionary.Elements elements;
    @XmlElement(required = true)
    protected Dictionary.ElementHierarchies elementHierarchies;
    @XmlElement(required = true)
    protected Dictionary.ResultTypes resultTypes;
    protected Dictionary.Stages stages;
    protected Dictionary.BiologyDescriptors biologyDescriptors;
    protected Dictionary.AssayDescriptors assayDescriptors;
    protected Dictionary.InstanceDescriptors instanceDescriptors;
    protected Dictionary.Laboratories laboratories;
    protected Dictionary.Units units;
    protected Dictionary.UnitConversions unitConversions;

    /**
     * Gets the value of the elements property.
     * 
     * @return
     *     possible object is
     *     {@link Dictionary.Elements }
     *     
     */
    public Dictionary.Elements getElements() {
        return elements;
    }

    /**
     * Sets the value of the elements property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dictionary.Elements }
     *     
     */
    public void setElements(Dictionary.Elements value) {
        this.elements = value;
    }

    /**
     * Gets the value of the elementHierarchies property.
     * 
     * @return
     *     possible object is
     *     {@link Dictionary.ElementHierarchies }
     *     
     */
    public Dictionary.ElementHierarchies getElementHierarchies() {
        return elementHierarchies;
    }

    /**
     * Sets the value of the elementHierarchies property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dictionary.ElementHierarchies }
     *     
     */
    public void setElementHierarchies(Dictionary.ElementHierarchies value) {
        this.elementHierarchies = value;
    }

    /**
     * Gets the value of the resultTypes property.
     * 
     * @return
     *     possible object is
     *     {@link Dictionary.ResultTypes }
     *     
     */
    public Dictionary.ResultTypes getResultTypes() {
        return resultTypes;
    }

    /**
     * Sets the value of the resultTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dictionary.ResultTypes }
     *     
     */
    public void setResultTypes(Dictionary.ResultTypes value) {
        this.resultTypes = value;
    }

    /**
     * Gets the value of the stages property.
     * 
     * @return
     *     possible object is
     *     {@link Dictionary.Stages }
     *     
     */
    public Dictionary.Stages getStages() {
        return stages;
    }

    /**
     * Sets the value of the stages property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dictionary.Stages }
     *     
     */
    public void setStages(Dictionary.Stages value) {
        this.stages = value;
    }

    /**
     * Gets the value of the biologyDescriptors property.
     * 
     * @return
     *     possible object is
     *     {@link Dictionary.BiologyDescriptors }
     *     
     */
    public Dictionary.BiologyDescriptors getBiologyDescriptors() {
        return biologyDescriptors;
    }

    /**
     * Sets the value of the biologyDescriptors property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dictionary.BiologyDescriptors }
     *     
     */
    public void setBiologyDescriptors(Dictionary.BiologyDescriptors value) {
        this.biologyDescriptors = value;
    }

    /**
     * Gets the value of the assayDescriptors property.
     * 
     * @return
     *     possible object is
     *     {@link Dictionary.AssayDescriptors }
     *     
     */
    public Dictionary.AssayDescriptors getAssayDescriptors() {
        return assayDescriptors;
    }

    /**
     * Sets the value of the assayDescriptors property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dictionary.AssayDescriptors }
     *     
     */
    public void setAssayDescriptors(Dictionary.AssayDescriptors value) {
        this.assayDescriptors = value;
    }

    /**
     * Gets the value of the instanceDescriptors property.
     * 
     * @return
     *     possible object is
     *     {@link Dictionary.InstanceDescriptors }
     *     
     */
    public Dictionary.InstanceDescriptors getInstanceDescriptors() {
        return instanceDescriptors;
    }

    /**
     * Sets the value of the instanceDescriptors property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dictionary.InstanceDescriptors }
     *     
     */
    public void setInstanceDescriptors(Dictionary.InstanceDescriptors value) {
        this.instanceDescriptors = value;
    }

    /**
     * Gets the value of the laboratories property.
     * 
     * @return
     *     possible object is
     *     {@link Dictionary.Laboratories }
     *     
     */
    public Dictionary.Laboratories getLaboratories() {
        return laboratories;
    }

    /**
     * Sets the value of the laboratories property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dictionary.Laboratories }
     *     
     */
    public void setLaboratories(Dictionary.Laboratories value) {
        this.laboratories = value;
    }

    /**
     * Gets the value of the units property.
     * 
     * @return
     *     possible object is
     *     {@link Dictionary.Units }
     *     
     */
    public Dictionary.Units getUnits() {
        return units;
    }

    /**
     * Sets the value of the units property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dictionary.Units }
     *     
     */
    public void setUnits(Dictionary.Units value) {
        this.units = value;
    }

    /**
     * Gets the value of the unitConversions property.
     * 
     * @return
     *     possible object is
     *     {@link Dictionary.UnitConversions }
     *     
     */
    public Dictionary.UnitConversions getUnitConversions() {
        return unitConversions;
    }

    /**
     * Sets the value of the unitConversions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Dictionary.UnitConversions }
     *     
     */
    public void setUnitConversions(Dictionary.UnitConversions value) {
        this.unitConversions = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="assayDescriptor" type="{}descriptorType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "assayDescriptor"
    })
    public static class AssayDescriptors {

        @XmlElement(required = true)
        protected List<DescriptorType> assayDescriptor;

        /**
         * Gets the value of the assayDescriptor property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the assayDescriptor property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAssayDescriptor().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DescriptorType }
         * 
         * 
         */
        public List<DescriptorType> getAssayDescriptor() {
            if (assayDescriptor == null) {
                assayDescriptor = new ArrayList<DescriptorType>();
            }
            return this.assayDescriptor;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="biologyDescriptor" type="{}descriptorType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "biologyDescriptor"
    })
    public static class BiologyDescriptors {

        @XmlElement(required = true)
        protected List<DescriptorType> biologyDescriptor;

        /**
         * Gets the value of the biologyDescriptor property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the biologyDescriptor property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBiologyDescriptor().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DescriptorType }
         * 
         * 
         */
        public List<DescriptorType> getBiologyDescriptor() {
            if (biologyDescriptor == null) {
                biologyDescriptor = new ArrayList<DescriptorType>();
            }
            return this.biologyDescriptor;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="elementHierarchy" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="relationshipType">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="supported by"/>
     *                         &lt;enumeration value="child of"/>
     *                         &lt;enumeration value="has_a"/>
     *                         &lt;enumeration value="derives from"/>
     *                         &lt;enumeration value="is_a"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="parentElementId" type="{}bardID" />
     *                 &lt;attribute name="childElementId" use="required" type="{}bardID" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "elementHierarchy"
    })
    public static class ElementHierarchies {

        @XmlElement(required = true)
        protected List<Dictionary.ElementHierarchies.ElementHierarchy> elementHierarchy;

        /**
         * Gets the value of the elementHierarchy property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the elementHierarchy property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getElementHierarchy().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Dictionary.ElementHierarchies.ElementHierarchy }
         * 
         * 
         */
        public List<Dictionary.ElementHierarchies.ElementHierarchy> getElementHierarchy() {
            if (elementHierarchy == null) {
                elementHierarchy = new ArrayList<Dictionary.ElementHierarchies.ElementHierarchy>();
            }
            return this.elementHierarchy;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="relationshipType">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="supported by"/>
         *               &lt;enumeration value="child of"/>
         *               &lt;enumeration value="has_a"/>
         *               &lt;enumeration value="derives from"/>
         *               &lt;enumeration value="is_a"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="parentElementId" type="{}bardID" />
         *       &lt;attribute name="childElementId" use="required" type="{}bardID" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "relationshipType"
        })
        public static class ElementHierarchy {

            @XmlElement(required = true)
            protected String relationshipType;
            @XmlAttribute(name = "parentElementId")
            protected BigInteger parentElementId;
            @XmlAttribute(name = "childElementId", required = true)
            protected BigInteger childElementId;

            /**
             * Gets the value of the relationshipType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getRelationshipType() {
                return relationshipType;
            }

            /**
             * Sets the value of the relationshipType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setRelationshipType(String value) {
                this.relationshipType = value;
            }

            /**
             * Gets the value of the parentElementId property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getParentElementId() {
                return parentElementId;
            }

            /**
             * Sets the value of the parentElementId property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setParentElementId(BigInteger value) {
                this.parentElementId = value;
            }

            /**
             * Gets the value of the childElementId property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getChildElementId() {
                return childElementId;
            }

            /**
             * Sets the value of the childElementId property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setChildElementId(BigInteger value) {
                this.childElementId = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}element" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "element"
    })
    public static class Elements {

        @XmlElement(required = true)
        protected List<Element> element;

        /**
         * Gets the value of the element property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the element property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getElement().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Element }
         * 
         * 
         */
        public List<Element> getElement() {
            if (element == null) {
                element = new ArrayList<Element>();
            }
            return this.element;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="instanceDescriptor" type="{}descriptorType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "instanceDescriptor"
    })
    public static class InstanceDescriptors {

        @XmlElement(required = true)
        protected List<DescriptorType> instanceDescriptor;

        /**
         * Gets the value of the instanceDescriptor property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the instanceDescriptor property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInstanceDescriptor().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DescriptorType }
         * 
         * 
         */
        public List<DescriptorType> getInstanceDescriptor() {
            if (instanceDescriptor == null) {
                instanceDescriptor = new ArrayList<DescriptorType>();
            }
            return this.instanceDescriptor;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="laboratory" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="laboratoryName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element ref="{}description" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="laboratoryId" use="required" type="{}bardID" />
     *                 &lt;attribute name="parentLaboratoryId" type="{}bardID" />
     *                 &lt;attribute name="laboratoryStatus" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "laboratory"
    })
    public static class Laboratories {

        @XmlElement(required = true)
        protected List<Dictionary.Laboratories.Laboratory> laboratory;

        /**
         * Gets the value of the laboratory property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the laboratory property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLaboratory().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Dictionary.Laboratories.Laboratory }
         * 
         * 
         */
        public List<Dictionary.Laboratories.Laboratory> getLaboratory() {
            if (laboratory == null) {
                laboratory = new ArrayList<Dictionary.Laboratories.Laboratory>();
            }
            return this.laboratory;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="laboratoryName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element ref="{}description" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attribute name="laboratoryId" use="required" type="{}bardID" />
         *       &lt;attribute name="parentLaboratoryId" type="{}bardID" />
         *       &lt;attribute name="laboratoryStatus" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "laboratoryName",
            "description"
        })
        public static class Laboratory {

            @XmlElement(required = true)
            protected String laboratoryName;
            @XmlElement(nillable = true)
            protected String description;
            @XmlAttribute(name = "laboratoryId", required = true)
            protected BigInteger laboratoryId;
            @XmlAttribute(name = "parentLaboratoryId")
            protected BigInteger parentLaboratoryId;
            @XmlAttribute(name = "laboratoryStatus", required = true)
            protected String laboratoryStatus;

            /**
             * Gets the value of the laboratoryName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLaboratoryName() {
                return laboratoryName;
            }

            /**
             * Sets the value of the laboratoryName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLaboratoryName(String value) {
                this.laboratoryName = value;
            }

            /**
             * Gets the value of the description property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDescription(String value) {
                this.description = value;
            }

            /**
             * Gets the value of the laboratoryId property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getLaboratoryId() {
                return laboratoryId;
            }

            /**
             * Sets the value of the laboratoryId property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setLaboratoryId(BigInteger value) {
                this.laboratoryId = value;
            }

            /**
             * Gets the value of the parentLaboratoryId property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getParentLaboratoryId() {
                return parentLaboratoryId;
            }

            /**
             * Sets the value of the parentLaboratoryId property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setParentLaboratoryId(BigInteger value) {
                this.parentLaboratoryId = value;
            }

            /**
             * Gets the value of the laboratoryStatus property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLaboratoryStatus() {
                return laboratoryStatus;
            }

            /**
             * Sets the value of the laboratoryStatus property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLaboratoryStatus(String value) {
                this.laboratoryStatus = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}resultType" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "resultType"
    })
    public static class ResultTypes {

        @XmlElement(required = true)
        protected List<ResultType> resultType;

        /**
         * Gets the value of the resultType property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the resultType property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getResultType().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ResultType }
         * 
         * 
         */
        public List<ResultType> getResultType() {
            if (resultType == null) {
                resultType = new ArrayList<ResultType>();
            }
            return this.resultType;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}stage" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "stage"
    })
    public static class Stages {

        @XmlElement(required = true)
        protected List<Stage> stage;

        /**
         * Gets the value of the stage property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the stage property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getStage().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Stage }
         * 
         * 
         */
        public List<Stage> getStage() {
            if (stage == null) {
                stage = new ArrayList<Stage>();
            }
            return this.stage;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="unitConversion" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="formula" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="fromUnit" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="toUnit" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="multiplier" type="{http://www.w3.org/2001/XMLSchema}double" />
     *                 &lt;attribute name="offset" type="{http://www.w3.org/2001/XMLSchema}double" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "unitConversion"
    })
    public static class UnitConversions {

        @XmlElement(required = true)
        protected List<Dictionary.UnitConversions.UnitConversion> unitConversion;

        /**
         * Gets the value of the unitConversion property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the unitConversion property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUnitConversion().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Dictionary.UnitConversions.UnitConversion }
         * 
         * 
         */
        public List<Dictionary.UnitConversions.UnitConversion> getUnitConversion() {
            if (unitConversion == null) {
                unitConversion = new ArrayList<Dictionary.UnitConversions.UnitConversion>();
            }
            return this.unitConversion;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="formula" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attribute name="fromUnit" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="toUnit" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="multiplier" type="{http://www.w3.org/2001/XMLSchema}double" />
         *       &lt;attribute name="offset" type="{http://www.w3.org/2001/XMLSchema}double" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "formula"
        })
        public static class UnitConversion {

            protected String formula;
            @XmlAttribute(name = "fromUnit", required = true)
            protected String fromUnit;
            @XmlAttribute(name = "toUnit", required = true)
            protected String toUnit;
            @XmlAttribute(name = "multiplier")
            protected Double multiplier;
            @XmlAttribute(name = "offset")
            protected Double offset;

            /**
             * Gets the value of the formula property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFormula() {
                return formula;
            }

            /**
             * Sets the value of the formula property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFormula(String value) {
                this.formula = value;
            }

            /**
             * Gets the value of the fromUnit property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFromUnit() {
                return fromUnit;
            }

            /**
             * Sets the value of the fromUnit property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFromUnit(String value) {
                this.fromUnit = value;
            }

            /**
             * Gets the value of the toUnit property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getToUnit() {
                return toUnit;
            }

            /**
             * Sets the value of the toUnit property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setToUnit(String value) {
                this.toUnit = value;
            }

            /**
             * Gets the value of the multiplier property.
             * 
             * @return
             *     possible object is
             *     {@link Double }
             *     
             */
            public Double getMultiplier() {
                return multiplier;
            }

            /**
             * Sets the value of the multiplier property.
             * 
             * @param value
             *     allowed object is
             *     {@link Double }
             *     
             */
            public void setMultiplier(Double value) {
                this.multiplier = value;
            }

            /**
             * Gets the value of the offset property.
             * 
             * @return
             *     possible object is
             *     {@link Double }
             *     
             */
            public Double getOffset() {
                return offset;
            }

            /**
             * Sets the value of the offset property.
             * 
             * @param value
             *     allowed object is
             *     {@link Double }
             *     
             */
            public void setOffset(Double value) {
                this.offset = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="unit" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{}description" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="unitId" use="required" type="{}bardID" />
     *                 &lt;attribute name="parentUnitId" type="{}bardID" />
     *                 &lt;attribute name="unit" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "unit"
    })
    public static class Units {

        @XmlElement(required = true)
        protected List<Dictionary.Units.Unit> unit;

        /**
         * Gets the value of the unit property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the unit property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getUnit().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Dictionary.Units.Unit }
         * 
         * 
         */
        public List<Dictionary.Units.Unit> getUnit() {
            if (unit == null) {
                unit = new ArrayList<Dictionary.Units.Unit>();
            }
            return this.unit;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{}description" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attribute name="unitId" use="required" type="{}bardID" />
         *       &lt;attribute name="parentUnitId" type="{}bardID" />
         *       &lt;attribute name="unit" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "description"
        })
        public static class Unit {

            @XmlElement(nillable = true)
            protected String description;
            @XmlAttribute(name = "unitId", required = true)
            protected BigInteger unitId;
            @XmlAttribute(name = "parentUnitId")
            protected BigInteger parentUnitId;
            @XmlAttribute(name = "unit", required = true)
            protected String unit;

            /**
             * Gets the value of the description property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDescription() {
                return description;
            }

            /**
             * Sets the value of the description property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDescription(String value) {
                this.description = value;
            }

            /**
             * Gets the value of the unitId property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getUnitId() {
                return unitId;
            }

            /**
             * Sets the value of the unitId property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setUnitId(BigInteger value) {
                this.unitId = value;
            }

            /**
             * Gets the value of the parentUnitId property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getParentUnitId() {
                return parentUnitId;
            }

            /**
             * Sets the value of the parentUnitId property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setParentUnitId(BigInteger value) {
                this.parentUnitId = value;
            }

            /**
             * Gets the value of the unit property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUnit() {
                return unit;
            }

            /**
             * Sets the value of the unit property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUnit(String value) {
                this.unit = value;
            }

        }

    }

}
