//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.25 at 12:13:33 AM EDT 
//


package gov.nih.ncgc.bard.capextract.jaxb;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for experimentContexType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="experimentContexType">
 *   &lt;complexContent>
 *     &lt;extension base="{}abstractContextType">
 *       &lt;sequence>
 *         &lt;element ref="{}experimentContextItems"/>
 *       &lt;/sequence>
 *       &lt;attribute name="experimentContextId" use="required" type="{}bardID" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "experimentContexType", propOrder = {
    "experimentContextItems"
})
public class ExperimentContexType
    extends AbstractContextType
{

    @XmlElement(required = true)
    protected ExperimentContextItems experimentContextItems;
    @XmlAttribute(required = true)
    protected BigInteger experimentContextId;

    /**
     * Gets the value of the experimentContextItems property.
     * 
     * @return
     *     possible object is
     *     {@link ExperimentContextItems }
     *     
     */
    public ExperimentContextItems getExperimentContextItems() {
        return experimentContextItems;
    }

    /**
     * Sets the value of the experimentContextItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExperimentContextItems }
     *     
     */
    public void setExperimentContextItems(ExperimentContextItems value) {
        this.experimentContextItems = value;
    }

    /**
     * Gets the value of the experimentContextId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getExperimentContextId() {
        return experimentContextId;
    }

    /**
     * Sets the value of the experimentContextId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setExperimentContextId(BigInteger value) {
        this.experimentContextId = value;
    }

}
