//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.14 at 01:23:56 PM EST 
//


package gov.nih.ncgc.bard.capextract.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import java.math.BigInteger;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="experimentMeasureId" use="required" type="{}bardID" />
 *       &lt;attribute name="measureRef" use="required" type="{}bardID" />
 *       &lt;attribute name="parentExperimentMeasureRef" type="{}bardID" />
 *       &lt;attribute name="parentChildRelationship" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "experimentMeasure")
public class ExperimentMeasure {

    @XmlAttribute(name = "experimentMeasureId", required = true)
    protected BigInteger experimentMeasureId;
    @XmlAttribute(name = "measureRef", required = true)
    protected BigInteger measureRef;
    @XmlAttribute(name = "parentExperimentMeasureRef")
    protected BigInteger parentExperimentMeasureRef;
    @XmlAttribute(name = "parentChildRelationship")
    @XmlSchemaType(name = "anySimpleType")
    protected String parentChildRelationship;

    /**
     * Gets the value of the experimentMeasureId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getExperimentMeasureId() {
        return experimentMeasureId;
    }

    /**
     * Sets the value of the experimentMeasureId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setExperimentMeasureId(BigInteger value) {
        this.experimentMeasureId = value;
    }

    /**
     * Gets the value of the measureRef property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMeasureRef() {
        return measureRef;
    }

    /**
     * Sets the value of the measureRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMeasureRef(BigInteger value) {
        this.measureRef = value;
    }

    /**
     * Gets the value of the parentExperimentMeasureRef property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getParentExperimentMeasureRef() {
        return parentExperimentMeasureRef;
    }

    /**
     * Sets the value of the parentExperimentMeasureRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setParentExperimentMeasureRef(BigInteger value) {
        this.parentExperimentMeasureRef = value;
    }

    /**
     * Gets the value of the parentChildRelationship property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentChildRelationship() {
        return parentChildRelationship;
    }

    /**
     * Sets the value of the parentChildRelationship property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentChildRelationship(String value) {
        this.parentChildRelationship = value;
    }

}
