//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.25 at 12:13:33 AM EDT 
//


package gov.nih.ncgc.bard.capextract.jaxb;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="resultTypeRef">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}link" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="label" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="statsModifierRef" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{}link" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="label" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="assayContextRefs" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="assayContextRef" type="{}bardID" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="childMeasureRefs" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="childMeasureRef" type="{}bardID" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="experimentMeasureId" use="required" type="{}bardID" />
 *       &lt;attribute name="parentExperimentMeasureRef" type="{}bardID" />
 *       &lt;attribute ref="{}parentChildRelationship"/>
 *       &lt;attribute name="priorityElement" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "resultTypeRef",
    "statsModifierRef",
    "assayContextRefs",
    "childMeasureRefs"
})
@XmlRootElement(name = "experimentMeasure")
public class ExperimentMeasure {

    @XmlElement(required = true)
    protected ExperimentMeasure.ResultTypeRef resultTypeRef;
    protected ExperimentMeasure.StatsModifierRef statsModifierRef;
    protected ExperimentMeasure.AssayContextRefs assayContextRefs;
    protected ExperimentMeasure.ChildMeasureRefs childMeasureRefs;
    @XmlAttribute(required = true)
    protected BigInteger experimentMeasureId;
    @XmlAttribute
    protected BigInteger parentExperimentMeasureRef;
    @XmlAttribute
    protected String parentChildRelationship;
    @XmlAttribute
    protected Boolean priorityElement;

    /**
     * Gets the value of the resultTypeRef property.
     * 
     * @return
     *     possible object is
     *     {@link ExperimentMeasure.ResultTypeRef }
     *     
     */
    public ExperimentMeasure.ResultTypeRef getResultTypeRef() {
        return resultTypeRef;
    }

    /**
     * Sets the value of the resultTypeRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExperimentMeasure.ResultTypeRef }
     *     
     */
    public void setResultTypeRef(ExperimentMeasure.ResultTypeRef value) {
        this.resultTypeRef = value;
    }

    /**
     * Gets the value of the statsModifierRef property.
     * 
     * @return
     *     possible object is
     *     {@link ExperimentMeasure.StatsModifierRef }
     *     
     */
    public ExperimentMeasure.StatsModifierRef getStatsModifierRef() {
        return statsModifierRef;
    }

    /**
     * Sets the value of the statsModifierRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExperimentMeasure.StatsModifierRef }
     *     
     */
    public void setStatsModifierRef(ExperimentMeasure.StatsModifierRef value) {
        this.statsModifierRef = value;
    }

    /**
     * Gets the value of the assayContextRefs property.
     * 
     * @return
     *     possible object is
     *     {@link ExperimentMeasure.AssayContextRefs }
     *     
     */
    public ExperimentMeasure.AssayContextRefs getAssayContextRefs() {
        return assayContextRefs;
    }

    /**
     * Sets the value of the assayContextRefs property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExperimentMeasure.AssayContextRefs }
     *     
     */
    public void setAssayContextRefs(ExperimentMeasure.AssayContextRefs value) {
        this.assayContextRefs = value;
    }

    /**
     * Gets the value of the childMeasureRefs property.
     * 
     * @return
     *     possible object is
     *     {@link ExperimentMeasure.ChildMeasureRefs }
     *     
     */
    public ExperimentMeasure.ChildMeasureRefs getChildMeasureRefs() {
        return childMeasureRefs;
    }

    /**
     * Sets the value of the childMeasureRefs property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExperimentMeasure.ChildMeasureRefs }
     *     
     */
    public void setChildMeasureRefs(ExperimentMeasure.ChildMeasureRefs value) {
        this.childMeasureRefs = value;
    }

    /**
     * Gets the value of the experimentMeasureId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getExperimentMeasureId() {
        return experimentMeasureId;
    }

    /**
     * Sets the value of the experimentMeasureId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setExperimentMeasureId(BigInteger value) {
        this.experimentMeasureId = value;
    }

    /**
     * Gets the value of the parentExperimentMeasureRef property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getParentExperimentMeasureRef() {
        return parentExperimentMeasureRef;
    }

    /**
     * Sets the value of the parentExperimentMeasureRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setParentExperimentMeasureRef(BigInteger value) {
        this.parentExperimentMeasureRef = value;
    }

    /**
     * Gets the value of the parentChildRelationship property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentChildRelationship() {
        return parentChildRelationship;
    }

    /**
     * Sets the value of the parentChildRelationship property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentChildRelationship(String value) {
        this.parentChildRelationship = value;
    }

    /**
     * Gets the value of the priorityElement property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isPriorityElement() {
        if (priorityElement == null) {
            return false;
        } else {
            return priorityElement;
        }
    }

    /**
     * Sets the value of the priorityElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPriorityElement(Boolean value) {
        this.priorityElement = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="assayContextRef" type="{}bardID" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "assayContextRef"
    })
    public static class AssayContextRefs {

        @XmlElement(required = true)
        protected List<BigInteger> assayContextRef;

        /**
         * Gets the value of the assayContextRef property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the assayContextRef property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getAssayContextRef().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BigInteger }
         * 
         * 
         */
        public List<BigInteger> getAssayContextRef() {
            if (assayContextRef == null) {
                assayContextRef = new ArrayList<BigInteger>();
            }
            return this.assayContextRef;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="childMeasureRef" type="{}bardID" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "childMeasureRef"
    })
    public static class ChildMeasureRefs {

        @XmlElement(required = true)
        protected List<BigInteger> childMeasureRef;

        /**
         * Gets the value of the childMeasureRef property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the childMeasureRef property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getChildMeasureRef().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BigInteger }
         * 
         * 
         */
        public List<BigInteger> getChildMeasureRef() {
            if (childMeasureRef == null) {
                childMeasureRef = new ArrayList<BigInteger>();
            }
            return this.childMeasureRef;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}link" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="label" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "link"
    })
    public static class ResultTypeRef {

        protected Link link;
        @XmlAttribute(required = true)
        protected String label;

        /**
         * Gets the value of the link property.
         * 
         * @return
         *     possible object is
         *     {@link Link }
         *     
         */
        public Link getLink() {
            return link;
        }

        /**
         * Sets the value of the link property.
         * 
         * @param value
         *     allowed object is
         *     {@link Link }
         *     
         */
        public void setLink(Link value) {
            this.link = value;
        }

        /**
         * Gets the value of the label property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLabel() {
            return label;
        }

        /**
         * Sets the value of the label property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLabel(String value) {
            this.label = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{}link" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="label" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "link"
    })
    public static class StatsModifierRef {

        protected Link link;
        @XmlAttribute(required = true)
        protected String label;

        /**
         * Gets the value of the link property.
         * 
         * @return
         *     possible object is
         *     {@link Link }
         *     
         */
        public Link getLink() {
            return link;
        }

        /**
         * Sets the value of the link property.
         * 
         * @param value
         *     allowed object is
         *     {@link Link }
         *     
         */
        public void setLink(Link value) {
            this.link = value;
        }

        /**
         * Gets the value of the label property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLabel() {
            return label;
        }

        /**
         * Sets the value of the label property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLabel(String value) {
            this.label = value;
        }

    }

}
