//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.19 at 08:44:47 AM EDT 
//


package gov.nih.ncgc.bard.capextract.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.nih.ncgc.bard.capextract.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Status_QNAME = new QName("", "status");
    private final static QName _Description_QNAME = new QName("", "description");
    private final static QName _Label_QNAME = new QName("", "label");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.nih.ncgc.bard.capextract.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Result }
     * 
     */
    public Result createResult() {
        return new Result();
    }

    /**
     * Create an instance of {@link ResultContextItems }
     * 
     */
    public ResultContextItems createResultContextItems() {
        return new ResultContextItems();
    }

    /**
     * Create an instance of {@link Assay }
     * 
     */
    public Assay createAssay() {
        return new Assay();
    }

    /**
     * Create an instance of {@link AssayContextItems }
     * 
     */
    public AssayContextItems createAssayContextItems() {
        return new AssayContextItems();
    }

    /**
     * Create an instance of {@link Dictionary }
     * 
     */
    public Dictionary createDictionary() {
        return new Dictionary();
    }

    /**
     * Create an instance of {@link Project }
     * 
     */
    public Project createProject() {
        return new Project();
    }

    /**
     * Create an instance of {@link Experiment }
     * 
     */
    public Experiment createExperiment() {
        return new Experiment();
    }

    /**
     * Create an instance of {@link Experiment.ExternalReferences }
     * 
     */
    public Experiment.ExternalReferences createExperimentExternalReferences() {
        return new Experiment.ExternalReferences();
    }

    /**
     * Create an instance of {@link Experiment.ExternalReferences.ExternalReference }
     * 
     */
    public Experiment.ExternalReferences.ExternalReference createExperimentExternalReferencesExternalReference() {
        return new Experiment.ExternalReferences.ExternalReference();
    }

    /**
     * Create an instance of {@link Experiment.ProjectSteps }
     * 
     */
    public Experiment.ProjectSteps createExperimentProjectSteps() {
        return new Experiment.ProjectSteps();
    }

    /**
     * Create an instance of {@link Experiment.ProjectSteps.ProjectStep }
     * 
     */
    public Experiment.ProjectSteps.ProjectStep createExperimentProjectStepsProjectStep() {
        return new Experiment.ProjectSteps.ProjectStep();
    }

    /**
     * Create an instance of {@link Experiment.ExperimentContextItems }
     * 
     */
    public Experiment.ExperimentContextItems createExperimentExperimentContextItems() {
        return new Experiment.ExperimentContextItems();
    }

    /**
     * Create an instance of {@link Experiment.ExperimentContextItems.ExperimentContextItem }
     * 
     */
    public Experiment.ExperimentContextItems.ExperimentContextItem createExperimentExperimentContextItemsExperimentContextItem() {
        return new Experiment.ExperimentContextItems.ExperimentContextItem();
    }

    /**
     * Create an instance of {@link Project.ProjectContextItems }
     * 
     */
    public Project.ProjectContextItems createProjectProjectContextItems() {
        return new Project.ProjectContextItems();
    }

    /**
     * Create an instance of {@link Project.ProjectContextItems.ProjectContextItem }
     * 
     */
    public Project.ProjectContextItems.ProjectContextItem createProjectProjectContextItemsProjectContextItem() {
        return new Project.ProjectContextItems.ProjectContextItem();
    }

    /**
     * Create an instance of {@link Project.ProjectSteps }
     * 
     */
    public Project.ProjectSteps createProjectProjectSteps() {
        return new Project.ProjectSteps();
    }

    /**
     * Create an instance of {@link Dictionary.UnitConversions }
     * 
     */
    public Dictionary.UnitConversions createDictionaryUnitConversions() {
        return new Dictionary.UnitConversions();
    }

    /**
     * Create an instance of {@link Dictionary.Units }
     * 
     */
    public Dictionary.Units createDictionaryUnits() {
        return new Dictionary.Units();
    }

    /**
     * Create an instance of {@link Dictionary.Laboratories }
     * 
     */
    public Dictionary.Laboratories createDictionaryLaboratories() {
        return new Dictionary.Laboratories();
    }

    /**
     * Create an instance of {@link Dictionary.ElementHierarchies }
     * 
     */
    public Dictionary.ElementHierarchies createDictionaryElementHierarchies() {
        return new Dictionary.ElementHierarchies();
    }

    /**
     * Create an instance of {@link Dictionary.ElementHierarchies.ElementHierarchy }
     * 
     */
    public Dictionary.ElementHierarchies.ElementHierarchy createDictionaryElementHierarchiesElementHierarchy() {
        return new Dictionary.ElementHierarchies.ElementHierarchy();
    }

    /**
     * Create an instance of {@link AssayContextItems.AssayContextItem }
     * 
     */
    public AssayContextItems.AssayContextItem createAssayContextItemsAssayContextItem() {
        return new AssayContextItems.AssayContextItem();
    }

    /**
     * Create an instance of {@link Assay.Measures }
     * 
     */
    public Assay.Measures createAssayMeasures() {
        return new Assay.Measures();
    }

    /**
     * Create an instance of {@link Assay.Measures.Measure }
     * 
     */
    public Assay.Measures.Measure createAssayMeasuresMeasure() {
        return new Assay.Measures.Measure();
    }

    /**
     * Create an instance of {@link Assay.AssayContexts }
     * 
     */
    public Assay.AssayContexts createAssayAssayContexts() {
        return new Assay.AssayContexts();
    }

    /**
     * Create an instance of {@link Result.ResultHierarchies }
     * 
     */
    public Result.ResultHierarchies createResultResultHierarchies() {
        return new Result.ResultHierarchies();
    }

    /**
     * Create an instance of {@link ResultContextItems.ResultContextItem }
     * 
     */
    public ResultContextItems.ResultContextItem createResultContextItemsResultContextItem() {
        return new ResultContextItems.ResultContextItem();
    }

    /**
     * Create an instance of {@link Result.ResultType }
     * 
     */
    public Result.ResultType createResultResultType() {
        return new Result.ResultType();
    }

    /**
     * Create an instance of {@link Result.Substance }
     * 
     */
    public Result.Substance createResultSubstance() {
        return new Result.Substance();
    }

    /**
     * Create an instance of {@link Link }
     * 
     */
    public Link createLink() {
        return new Link();
    }

    /**
     * Create an instance of {@link Element }
     * 
     */
    public Element createElement() {
        return new Element();
    }

    /**
     * Create an instance of {@link Assay.AssayDocuments }
     * 
     */
    public Assay.AssayDocuments createAssayAssayDocuments() {
        return new Assay.AssayDocuments();
    }

    /**
     * Create an instance of {@link Dictionary.Elements }
     * 
     */
    public Dictionary.Elements createDictionaryElements() {
        return new Dictionary.Elements();
    }

    /**
     * Create an instance of {@link Dictionary.ResultTypes }
     * 
     */
    public Dictionary.ResultTypes createDictionaryResultTypes() {
        return new Dictionary.ResultTypes();
    }

    /**
     * Create an instance of {@link Dictionary.Stages }
     * 
     */
    public Dictionary.Stages createDictionaryStages() {
        return new Dictionary.Stages();
    }

    /**
     * Create an instance of {@link Dictionary.Descriptors }
     * 
     */
    public Dictionary.Descriptors createDictionaryDescriptors() {
        return new Dictionary.Descriptors();
    }

    /**
     * Create an instance of {@link Bardexport }
     * 
     */
    public Bardexport createBardexport() {
        return new Bardexport();
    }

    /**
     * Create an instance of {@link Stage }
     * 
     */
    public Stage createStage() {
        return new Stage();
    }

    /**
     * Create an instance of {@link Assays }
     * 
     */
    public Assays createAssays() {
        return new Assays();
    }

    /**
     * Create an instance of {@link Projects }
     * 
     */
    public Projects createProjects() {
        return new Projects();
    }

    /**
     * Create an instance of {@link AssayDocument }
     * 
     */
    public AssayDocument createAssayDocument() {
        return new AssayDocument();
    }

    /**
     * Create an instance of {@link Results }
     * 
     */
    public Results createResults() {
        return new Results();
    }

    /**
     * Create an instance of {@link Experiments }
     * 
     */
    public Experiments createExperiments() {
        return new Experiments();
    }

    /**
     * Create an instance of {@link gov.nih.ncgc.bard.capextract.jaxb.ResultType }
     * 
     */
    public gov.nih.ncgc.bard.capextract.jaxb.ResultType createResultType() {
        return new gov.nih.ncgc.bard.capextract.jaxb.ResultType();
    }

    /**
     * Create an instance of {@link DescriptorType }
     * 
     */
    public DescriptorType createDescriptorType() {
        return new DescriptorType();
    }

    /**
     * Create an instance of {@link Experiment.ExternalReferences.ExternalReference.ExternalSystem }
     * 
     */
    public Experiment.ExternalReferences.ExternalReference.ExternalSystem createExperimentExternalReferencesExternalReferenceExternalSystem() {
        return new Experiment.ExternalReferences.ExternalReference.ExternalSystem();
    }

    /**
     * Create an instance of {@link Experiment.ProjectSteps.ProjectStep.PrecedingExperiment }
     * 
     */
    public Experiment.ProjectSteps.ProjectStep.PrecedingExperiment createExperimentProjectStepsProjectStepPrecedingExperiment() {
        return new Experiment.ProjectSteps.ProjectStep.PrecedingExperiment();
    }

    /**
     * Create an instance of {@link Experiment.ExperimentContextItems.ExperimentContextItem.Attribute }
     * 
     */
    public Experiment.ExperimentContextItems.ExperimentContextItem.Attribute createExperimentExperimentContextItemsExperimentContextItemAttribute() {
        return new Experiment.ExperimentContextItems.ExperimentContextItem.Attribute();
    }

    /**
     * Create an instance of {@link Experiment.ExperimentContextItems.ExperimentContextItem.ValueControlled }
     * 
     */
    public Experiment.ExperimentContextItems.ExperimentContextItem.ValueControlled createExperimentExperimentContextItemsExperimentContextItemValueControlled() {
        return new Experiment.ExperimentContextItems.ExperimentContextItem.ValueControlled();
    }

    /**
     * Create an instance of {@link Project.ProjectContextItems.ProjectContextItem.Attribute }
     * 
     */
    public Project.ProjectContextItems.ProjectContextItem.Attribute createProjectProjectContextItemsProjectContextItemAttribute() {
        return new Project.ProjectContextItems.ProjectContextItem.Attribute();
    }

    /**
     * Create an instance of {@link Project.ProjectContextItems.ProjectContextItem.ValueControlled }
     * 
     */
    public Project.ProjectContextItems.ProjectContextItem.ValueControlled createProjectProjectContextItemsProjectContextItemValueControlled() {
        return new Project.ProjectContextItems.ProjectContextItem.ValueControlled();
    }

    /**
     * Create an instance of {@link Project.ProjectSteps.ProjectStep }
     * 
     */
    public Project.ProjectSteps.ProjectStep createProjectProjectStepsProjectStep() {
        return new Project.ProjectSteps.ProjectStep();
    }

    /**
     * Create an instance of {@link Dictionary.UnitConversions.UnitConversion }
     * 
     */
    public Dictionary.UnitConversions.UnitConversion createDictionaryUnitConversionsUnitConversion() {
        return new Dictionary.UnitConversions.UnitConversion();
    }

    /**
     * Create an instance of {@link Dictionary.Units.Unit }
     * 
     */
    public Dictionary.Units.Unit createDictionaryUnitsUnit() {
        return new Dictionary.Units.Unit();
    }

    /**
     * Create an instance of {@link Dictionary.Laboratories.Laboratory }
     * 
     */
    public Dictionary.Laboratories.Laboratory createDictionaryLaboratoriesLaboratory() {
        return new Dictionary.Laboratories.Laboratory();
    }

    /**
     * Create an instance of {@link Dictionary.ElementHierarchies.ElementHierarchy.ChildElement }
     * 
     */
    public Dictionary.ElementHierarchies.ElementHierarchy.ChildElement createDictionaryElementHierarchiesElementHierarchyChildElement() {
        return new Dictionary.ElementHierarchies.ElementHierarchy.ChildElement();
    }

    /**
     * Create an instance of {@link Dictionary.ElementHierarchies.ElementHierarchy.ParentElement }
     * 
     */
    public Dictionary.ElementHierarchies.ElementHierarchy.ParentElement createDictionaryElementHierarchiesElementHierarchyParentElement() {
        return new Dictionary.ElementHierarchies.ElementHierarchy.ParentElement();
    }

    /**
     * Create an instance of {@link AssayContextItems.AssayContextItem.ValueId }
     * 
     */
    public AssayContextItems.AssayContextItem.ValueId createAssayContextItemsAssayContextItemValueId() {
        return new AssayContextItems.AssayContextItem.ValueId();
    }

    /**
     * Create an instance of {@link AssayContextItems.AssayContextItem.AttributeId }
     * 
     */
    public AssayContextItems.AssayContextItem.AttributeId createAssayContextItemsAssayContextItemAttributeId() {
        return new AssayContextItems.AssayContextItem.AttributeId();
    }

    /**
     * Create an instance of {@link Assay.Measures.Measure.ResultTypeRef }
     * 
     */
    public Assay.Measures.Measure.ResultTypeRef createAssayMeasuresMeasureResultTypeRef() {
        return new Assay.Measures.Measure.ResultTypeRef();
    }

    /**
     * Create an instance of {@link Assay.Measures.Measure.EntryUnit }
     * 
     */
    public Assay.Measures.Measure.EntryUnit createAssayMeasuresMeasureEntryUnit() {
        return new Assay.Measures.Measure.EntryUnit();
    }

    /**
     * Create an instance of {@link Assay.AssayContexts.AssayContext }
     * 
     */
    public Assay.AssayContexts.AssayContext createAssayAssayContextsAssayContext() {
        return new Assay.AssayContexts.AssayContext();
    }

    /**
     * Create an instance of {@link Result.ResultHierarchies.ResultHierarchy }
     * 
     */
    public Result.ResultHierarchies.ResultHierarchy createResultResultHierarchiesResultHierarchy() {
        return new Result.ResultHierarchies.ResultHierarchy();
    }

    /**
     * Create an instance of {@link ResultContextItems.ResultContextItem.Attribute }
     * 
     */
    public ResultContextItems.ResultContextItem.Attribute createResultContextItemsResultContextItemAttribute() {
        return new ResultContextItems.ResultContextItem.Attribute();
    }

    /**
     * Create an instance of {@link ResultContextItems.ResultContextItem.ValueControlled }
     * 
     */
    public ResultContextItems.ResultContextItem.ValueControlled createResultContextItemsResultContextItemValueControlled() {
        return new ResultContextItems.ResultContextItem.ValueControlled();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "status")
    public JAXBElement<String> createStatus(String value) {
        return new JAXBElement<String>(_Status_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "label")
    public JAXBElement<String> createLabel(String value) {
        return new JAXBElement<String>(_Label_QNAME, String.class, null, value);
    }

}
