//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.01 at 12:02:20 PM EST 
//


package gov.nih.ncgc.bard.capextract.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.nih.ncgc.bard.capextract.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AssayDocument_QNAME = new QName("", "assayDocument");
    private final static QName _Status_QNAME = new QName("", "status");
    private final static QName _AssayContextItem_QNAME = new QName("", "assayContextItem");
    private final static QName _Description_QNAME = new QName("", "description");
    private final static QName _Context_QNAME = new QName("", "context");
    private final static QName _ProjectDocument_QNAME = new QName("", "projectDocument");
    private final static QName _Label_QNAME = new QName("", "label");
    private final static QName _AssayContext_QNAME = new QName("", "assayContext");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.nih.ncgc.bard.capextract.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Result }
     * 
     */
    public Result createResult() {
        return new Result();
    }

    /**
     * Create an instance of {@link ResultContextItems }
     * 
     */
    public ResultContextItems createResultContextItems() {
        return new ResultContextItems();
    }

    /**
     * Create an instance of {@link Experiment }
     * 
     */
    public Experiment createExperiment() {
        return new Experiment();
    }

    /**
     * Create an instance of {@link ExternalSystems }
     * 
     */
    public ExternalSystems createExternalSystems() {
        return new ExternalSystems();
    }

    /**
     * Create an instance of {@link Assay }
     * 
     */
    public Assay createAssay() {
        return new Assay();
    }

    /**
     * Create an instance of {@link ExternalReferences }
     * 
     */
    public ExternalReferences createExternalReferences() {
        return new ExternalReferences();
    }

    /**
     * Create an instance of {@link Dictionary }
     * 
     */
    public Dictionary createDictionary() {
        return new Dictionary();
    }

    /**
     * Create an instance of {@link Project }
     * 
     */
    public Project createProject() {
        return new Project();
    }

    /**
     * Create an instance of {@link ProjectExperiment }
     * 
     */
    public ProjectExperiment createProjectExperiment() {
        return new ProjectExperiment();
    }

    /**
     * Create an instance of {@link Dictionary.UnitConversions }
     * 
     */
    public Dictionary.UnitConversions createDictionaryUnitConversions() {
        return new Dictionary.UnitConversions();
    }

    /**
     * Create an instance of {@link Dictionary.Units }
     * 
     */
    public Dictionary.Units createDictionaryUnits() {
        return new Dictionary.Units();
    }

    /**
     * Create an instance of {@link Dictionary.Laboratories }
     * 
     */
    public Dictionary.Laboratories createDictionaryLaboratories() {
        return new Dictionary.Laboratories();
    }

    /**
     * Create an instance of {@link Dictionary.ElementHierarchies }
     * 
     */
    public Dictionary.ElementHierarchies createDictionaryElementHierarchies() {
        return new Dictionary.ElementHierarchies();
    }

    /**
     * Create an instance of {@link Dictionary.ElementHierarchies.ElementHierarchy }
     * 
     */
    public Dictionary.ElementHierarchies.ElementHierarchy createDictionaryElementHierarchiesElementHierarchy() {
        return new Dictionary.ElementHierarchies.ElementHierarchy();
    }

    /**
     * Create an instance of {@link Assay.Measures }
     * 
     */
    public Assay.Measures createAssayMeasures() {
        return new Assay.Measures();
    }

    /**
     * Create an instance of {@link Assay.Measures.Measure }
     * 
     */
    public Assay.Measures.Measure createAssayMeasuresMeasure() {
        return new Assay.Measures.Measure();
    }

    /**
     * Create an instance of {@link AssayContexType }
     * 
     */
    public AssayContexType createAssayContexType() {
        return new AssayContexType();
    }

    /**
     * Create an instance of {@link ContextType }
     * 
     */
    public ContextType createContextType() {
        return new ContextType();
    }

    /**
     * Create an instance of {@link Result.ResultHierarchies }
     * 
     */
    public Result.ResultHierarchies createResultResultHierarchies() {
        return new Result.ResultHierarchies();
    }

    /**
     * Create an instance of {@link ResultContextItems.ResultContextItem }
     * 
     */
    public ResultContextItems.ResultContextItem createResultContextItemsResultContextItem() {
        return new ResultContextItems.ResultContextItem();
    }

    /**
     * Create an instance of {@link Result.ResultType }
     * 
     */
    public Result.ResultType createResultResultType() {
        return new Result.ResultType();
    }

    /**
     * Create an instance of {@link Result.Substance }
     * 
     */
    public Result.Substance createResultSubstance() {
        return new Result.Substance();
    }

    /**
     * Create an instance of {@link Link }
     * 
     */
    public Link createLink() {
        return new Link();
    }

    /**
     * Create an instance of {@link ExperimentContextItems }
     * 
     */
    public ExperimentContextItems createExperimentContextItems() {
        return new ExperimentContextItems();
    }

    /**
     * Create an instance of {@link ExperimentContextItemType }
     * 
     */
    public ExperimentContextItemType createExperimentContextItemType() {
        return new ExperimentContextItemType();
    }

    /**
     * Create an instance of {@link ProjectSteps }
     * 
     */
    public ProjectSteps createProjectSteps() {
        return new ProjectSteps();
    }

    /**
     * Create an instance of {@link ProjectStep }
     * 
     */
    public ProjectStep createProjectStep() {
        return new ProjectStep();
    }

    /**
     * Create an instance of {@link Contexts }
     * 
     */
    public Contexts createContexts() {
        return new Contexts();
    }

    /**
     * Create an instance of {@link Bardexport }
     * 
     */
    public Bardexport createBardexport() {
        return new Bardexport();
    }

    /**
     * Create an instance of {@link Stage }
     * 
     */
    public Stage createStage() {
        return new Stage();
    }

    /**
     * Create an instance of {@link AssayContextItems }
     * 
     */
    public AssayContextItems createAssayContextItems() {
        return new AssayContextItems();
    }

    /**
     * Create an instance of {@link AssayContextItemType }
     * 
     */
    public AssayContextItemType createAssayContextItemType() {
        return new AssayContextItemType();
    }

    /**
     * Create an instance of {@link Results }
     * 
     */
    public Results createResults() {
        return new Results();
    }

    /**
     * Create an instance of {@link Experiments }
     * 
     */
    public Experiments createExperiments() {
        return new Experiments();
    }

    /**
     * Create an instance of {@link Experiment.ExperimentMeasures }
     * 
     */
    public Experiment.ExperimentMeasures createExperimentExperimentMeasures() {
        return new Experiment.ExperimentMeasures();
    }

    /**
     * Create an instance of {@link DocumentType }
     * 
     */
    public DocumentType createDocumentType() {
        return new DocumentType();
    }

    /**
     * Create an instance of {@link ExperimentMeasure }
     * 
     */
    public ExperimentMeasure createExperimentMeasure() {
        return new ExperimentMeasure();
    }

    /**
     * Create an instance of {@link ExternalSystems.ExternalSystem }
     * 
     */
    public ExternalSystems.ExternalSystem createExternalSystemsExternalSystem() {
        return new ExternalSystems.ExternalSystem();
    }

    /**
     * Create an instance of {@link Element }
     * 
     */
    public Element createElement() {
        return new Element();
    }

    /**
     * Create an instance of {@link Assay.AssayContexts }
     * 
     */
    public Assay.AssayContexts createAssayAssayContexts() {
        return new Assay.AssayContexts();
    }

    /**
     * Create an instance of {@link ExternalReferences.ExternalReference }
     * 
     */
    public ExternalReferences.ExternalReference createExternalReferencesExternalReference() {
        return new ExternalReferences.ExternalReference();
    }

    /**
     * Create an instance of {@link Dictionary.Elements }
     * 
     */
    public Dictionary.Elements createDictionaryElements() {
        return new Dictionary.Elements();
    }

    /**
     * Create an instance of {@link Dictionary.ResultTypes }
     * 
     */
    public Dictionary.ResultTypes createDictionaryResultTypes() {
        return new Dictionary.ResultTypes();
    }

    /**
     * Create an instance of {@link Dictionary.Stages }
     * 
     */
    public Dictionary.Stages createDictionaryStages() {
        return new Dictionary.Stages();
    }

    /**
     * Create an instance of {@link Dictionary.Descriptors }
     * 
     */
    public Dictionary.Descriptors createDictionaryDescriptors() {
        return new Dictionary.Descriptors();
    }

    /**
     * Create an instance of {@link Assays }
     * 
     */
    public Assays createAssays() {
        return new Assays();
    }

    /**
     * Create an instance of {@link Projects }
     * 
     */
    public Projects createProjects() {
        return new Projects();
    }

    /**
     * Create an instance of {@link Project.ProjectExperiments }
     * 
     */
    public Project.ProjectExperiments createProjectProjectExperiments() {
        return new Project.ProjectExperiments();
    }

    /**
     * Create an instance of {@link ProjectExperiment.ExperimentRef }
     * 
     */
    public ProjectExperiment.ExperimentRef createProjectExperimentExperimentRef() {
        return new ProjectExperiment.ExperimentRef();
    }

    /**
     * Create an instance of {@link ProjectExperiment.StageRef }
     * 
     */
    public ProjectExperiment.StageRef createProjectExperimentStageRef() {
        return new ProjectExperiment.StageRef();
    }

    /**
     * Create an instance of {@link gov.nih.ncgc.bard.capextract.jaxb.ResultType }
     * 
     */
    public gov.nih.ncgc.bard.capextract.jaxb.ResultType createResultType() {
        return new gov.nih.ncgc.bard.capextract.jaxb.ResultType();
    }

    /**
     * Create an instance of {@link ContextItemType }
     * 
     */
    public ContextItemType createContextItemType() {
        return new ContextItemType();
    }

    /**
     * Create an instance of {@link ExperimentContexType }
     * 
     */
    public ExperimentContexType createExperimentContexType() {
        return new ExperimentContexType();
    }

    /**
     * Create an instance of {@link DescriptorType }
     * 
     */
    public DescriptorType createDescriptorType() {
        return new DescriptorType();
    }

    /**
     * Create an instance of {@link gov.nih.ncgc.bard.capextract.jaxb.AbstractContextItemType.ValueId }
     * 
     */
    public gov.nih.ncgc.bard.capextract.jaxb.AbstractContextItemType.ValueId createAbstractContextItemTypeValueId() {
        return new gov.nih.ncgc.bard.capextract.jaxb.AbstractContextItemType.ValueId();
    }

    /**
     * Create an instance of {@link gov.nih.ncgc.bard.capextract.jaxb.AbstractContextItemType.AttributeId }
     * 
     */
    public gov.nih.ncgc.bard.capextract.jaxb.AbstractContextItemType.AttributeId createAbstractContextItemTypeAttributeId() {
        return new gov.nih.ncgc.bard.capextract.jaxb.AbstractContextItemType.AttributeId();
    }

    /**
     * Create an instance of {@link Dictionary.UnitConversions.UnitConversion }
     * 
     */
    public Dictionary.UnitConversions.UnitConversion createDictionaryUnitConversionsUnitConversion() {
        return new Dictionary.UnitConversions.UnitConversion();
    }

    /**
     * Create an instance of {@link Dictionary.Units.Unit }
     * 
     */
    public Dictionary.Units.Unit createDictionaryUnitsUnit() {
        return new Dictionary.Units.Unit();
    }

    /**
     * Create an instance of {@link Dictionary.Laboratories.Laboratory }
     * 
     */
    public Dictionary.Laboratories.Laboratory createDictionaryLaboratoriesLaboratory() {
        return new Dictionary.Laboratories.Laboratory();
    }

    /**
     * Create an instance of {@link Dictionary.ElementHierarchies.ElementHierarchy.ChildElement }
     * 
     */
    public Dictionary.ElementHierarchies.ElementHierarchy.ChildElement createDictionaryElementHierarchiesElementHierarchyChildElement() {
        return new Dictionary.ElementHierarchies.ElementHierarchy.ChildElement();
    }

    /**
     * Create an instance of {@link Dictionary.ElementHierarchies.ElementHierarchy.ParentElement }
     * 
     */
    public Dictionary.ElementHierarchies.ElementHierarchy.ParentElement createDictionaryElementHierarchiesElementHierarchyParentElement() {
        return new Dictionary.ElementHierarchies.ElementHierarchy.ParentElement();
    }

    /**
     * Create an instance of {@link Assay.Measures.Measure.ResultTypeRef }
     * 
     */
    public Assay.Measures.Measure.ResultTypeRef createAssayMeasuresMeasureResultTypeRef() {
        return new Assay.Measures.Measure.ResultTypeRef();
    }

    /**
     * Create an instance of {@link Assay.Measures.Measure.StatsModifierRef }
     * 
     */
    public Assay.Measures.Measure.StatsModifierRef createAssayMeasuresMeasureStatsModifierRef() {
        return new Assay.Measures.Measure.StatsModifierRef();
    }

    /**
     * Create an instance of {@link Assay.Measures.Measure.EntryUnitRef }
     * 
     */
    public Assay.Measures.Measure.EntryUnitRef createAssayMeasuresMeasureEntryUnitRef() {
        return new Assay.Measures.Measure.EntryUnitRef();
    }

    /**
     * Create an instance of {@link Assay.Measures.Measure.AssayContextRefs }
     * 
     */
    public Assay.Measures.Measure.AssayContextRefs createAssayMeasuresMeasureAssayContextRefs() {
        return new Assay.Measures.Measure.AssayContextRefs();
    }

    /**
     * Create an instance of {@link AssayContexType.MeasureRefs }
     * 
     */
    public AssayContexType.MeasureRefs createAssayContexTypeMeasureRefs() {
        return new AssayContexType.MeasureRefs();
    }

    /**
     * Create an instance of {@link ContextType.ContextItems }
     * 
     */
    public ContextType.ContextItems createContextTypeContextItems() {
        return new ContextType.ContextItems();
    }

    /**
     * Create an instance of {@link Result.ResultHierarchies.ResultHierarchy }
     * 
     */
    public Result.ResultHierarchies.ResultHierarchy createResultResultHierarchiesResultHierarchy() {
        return new Result.ResultHierarchies.ResultHierarchy();
    }

    /**
     * Create an instance of {@link ResultContextItems.ResultContextItem.Attribute }
     * 
     */
    public ResultContextItems.ResultContextItem.Attribute createResultContextItemsResultContextItemAttribute() {
        return new ResultContextItems.ResultContextItem.Attribute();
    }

    /**
     * Create an instance of {@link ResultContextItems.ResultContextItem.ValueControlled }
     * 
     */
    public ResultContextItems.ResultContextItem.ValueControlled createResultContextItemsResultContextItemValueControlled() {
        return new ResultContextItems.ResultContextItem.ValueControlled();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DocumentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "assayDocument")
    public JAXBElement<DocumentType> createAssayDocument(DocumentType value) {
        return new JAXBElement<DocumentType>(_AssayDocument_QNAME, DocumentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "status")
    public JAXBElement<String> createStatus(String value) {
        return new JAXBElement<String>(_Status_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AssayContextItemType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "assayContextItem")
    public JAXBElement<AssayContextItemType> createAssayContextItem(AssayContextItemType value) {
        return new JAXBElement<AssayContextItemType>(_AssayContextItem_QNAME, AssayContextItemType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContextType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "context")
    public JAXBElement<ContextType> createContext(ContextType value) {
        return new JAXBElement<ContextType>(_Context_QNAME, ContextType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DocumentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "projectDocument")
    public JAXBElement<DocumentType> createProjectDocument(DocumentType value) {
        return new JAXBElement<DocumentType>(_ProjectDocument_QNAME, DocumentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "label")
    public JAXBElement<String> createLabel(String value) {
        return new JAXBElement<String>(_Label_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AssayContexType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "assayContext")
    public JAXBElement<AssayContexType> createAssayContext(AssayContexType value) {
        return new JAXBElement<AssayContexType>(_AssayContext_QNAME, AssayContexType.class, null, value);
    }

}
